require "rms_web_service/response/shop_management/parser"
require "rms_web_service/response/shop_management/status"
require "rms_web_service/response/shop_management/design/description/large/list/get"
require "rms_web_service/response/shop_management/design/description/small/list/get"
require "rms_web_service/response/shop_management/design/featured/item/list/get"
require "rms_web_service/response/shop_management/design/navi_template/list/get"
